name: Changed formatters
on: [pull_request]
jobs:
  formatters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debugging
        run: |
          git rev-parse HEAD
          git status
          git branch -avv
          git show master:apheleia.el
      - name: Test changed formatters
        run: |
          set -euo pipefail

          mkdir -p .tmp
          make docker CMD="make fmt-changed > .tmp/changed"
          export FORMATTERS="$(< .tmp/changed)"
          if [[ -n "${FORMATTERS}" ]]; then
              make fmt-build fmt-docker CMD="make fmt-test"
          fi
