name: Lint
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [27, 28, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linters
        env:
          VERSION: ${{ matrix.emacs_version }}
        run: >-
          make docker CMD="make lint"
