name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [25, 26, 27, "master"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run linters
        env:
          VERSION: ${{ matrix.emacs_version }}
        run: >-
          make docker CMD="make lint"
