name: Tests and linters
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [27, 28, 29, 30]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # No shallow clone, we want to be able to compare PR branch
          # to main.
          fetch-depth: 0
      - name: Run linters
        env:
          VERSION: ${{ matrix.emacs_version }}
        run: >-
          make docker CMD="make unit integration lint lint-changelog"
